export const projects = [
{slug:'mood',title:'Mood',category:'Mobile UX · Event discovery',role:'UX & interface design',format:'Low-fidelity wireframes and visual prototype',summary:'A mobile journey from finding a local event to keeping the ticket ready.',deck:'Designing an event app around a complete task: discover something to do, narrow the options, and book a ticket.',cover:['mood-home','mood-events','mood-tickets'],tone:'purple',overview:'Mood brings local event discovery and ticket purchasing into one mobile experience. The project explores how people move between browsing, filtering, event details, checkout, and their tickets.',sections:[
{title:'Start with the journey',text:'The low-fidelity work establishes the core screens before adding a visual style. Event listings lead to details, then through cart and checkout to a confirmation. Account and ticket screens give the purchase a destination after checkout.',images:[['mood-low-events','Low-fidelity event listing'],['mood-low-filters','Early filter structure'],['mood-low-detail','Low-fidelity event details']]},
{title:'Make the choices visible',text:'The visual prototype uses event imagery and a dark interface to distinguish individual listings. Filtering develops from days of the week into a date range, genre, and venue. Applied filter chips make the selected criteria visible when returning to results.',images:[['mood-home','Mood home screen'],['mood-events','Event discovery'],['mood-filters','Date, genre, and venue filters'],['mood-filtered','Results with applied filters']]},
{title:'Design beyond the purchase button',text:'The flow continues through event details, payment, confirmation, and saved tickets. The prototype also includes account creation and empty states, considering what people encounter before and after a purchase.',images:[['mood-detail','Event details and ticket selection'],['mood-checkout','Checkout'],['mood-confirmation','Purchase confirmation'],['mood-tickets','Saved tickets'],['mood-empty-account','Account empty state']]}
],outcome:'This work demonstrates a connected mobile task flow, progression from wireframes to a visual prototype, and attention to the states around a transaction. Usability testing would be the next step to validate the flow.',source:'Academic concept. Original files: Mood low fi wireframe.fig and mood prototype.fig. Screens show the supplied designs; no conversion or usability results are claimed.'},
{slug:'art-history',title:'Journey Through Design',category:'Collaborative UX · Art history',role:'Contributing designer & usability testing',format:'Team design system and interactive prototype',summary:'Helping people explore art through timelines, artists, and individual works.',deck:'A collaborative art history experience that connects browsing, search, and filters with deeper exploration of artists and their work.',cover:['art-history-home'],tone:'blue',overview:'Created with GIT 540 Team 9, Journey Through Design offers several ways into art history: explore a timeline, search for a subject, or narrow a collection with filters. The shared Figma project contains a design system, wireframes, developed screens, interactive work, and research notes.',credit:'My role: contributing designer and usability testing. The project is a team effort; the screens shown here are shared team outputs. The source includes usability-testing notes credited to Darrell, which ground the observations below.',sections:[
{title:'Connect different ways to explore',text:'The timeline provides a broad historical entry point. Filters for time period, nationality, movement, and artist support a more specific search. Artist and artwork pages extend the journey from an overview into a focused subject.',images:[['art-history-timeline','Timeline exploration — team design'],['art-history-filters','Collection filters — team design']]},
{title:'Use testing to question navigation',text:'In the mid-fidelity testing notes credited to me, the participant could complete the first task but did not always know how to return. “Going back” was identified as confusing. Filter categories also needed clarification. These observations point toward clearer return paths and more understandable filter choices.',images:[['art-history-testing-notes','Mid-fidelity testing notes credited to Darrell'],['art-history-artist','Artist page — team design']]},
{title:'Build a consistent visual language',text:'The team’s design system combines Taviraj and Gantari typography with a blue and red palette. Repeated navigation, cards, and controls connect the different page types. Later testing notes credited to me record successful navigation through gallery, search, timeline filters, and artwork; these are qualitative observations from testing, rather than proof of broad usability gains.',images:[['art-history-typography','Shared typography system'],['art-history-colors','Shared color palette'],['art-history-search','Search — team design'],['art-history-artwork','Artwork detail — team design']]}
],outcome:'The project connects collaborative interface design with task-based testing. My documented testing contributions show how observations about navigation and filter clarity can inform a team’s next iteration.',source:'Collaborative academic project, GIT 540 Team 9. Original file: collaborative project building art history app.fig. Individual authorship is not assigned to screens where the source does not establish it.'},
{slug:'bakery',title:'Rose Family Bakery POS',category:'Product UX · Tablet ordering',role:'UX & wireframe design',format:'Low- and mid-fidelity tablet interfaces',summary:'Structuring custom bakery orders from product choices through payment.',deck:'A point-of-sale ordering flow that keeps a custom order visible while staff work through its details.',cover:['bakery-low-dashboard'],tone:'peach',overview:'Custom bakery orders combine product selection, personalization, timing, and payment. This tablet concept organizes those decisions into a staged flow and uses a persistent order summary to keep the current order in view.',sections:[
{title:'Give a complex order a clear structure',text:'The low-fidelity screens establish a dashboard and a five-stage order flow, covering setup, products, review, customer and payment details, and confirmation. The ordering rules include at least 48 hours of lead time and scheduling up to 60 days ahead.',images:[['bakery-low-dashboard','Low-fidelity dashboard'],['bakery-low-products','Early product selection']]},
{title:'Keep customization within the order',text:'The mid-fidelity work develops order type, product categories, and custom cake options. Size, flavor, theme, quantity, and a message of up to 50 characters sit alongside the current order. The layout gives staff a place to check the order while configuring a product.',images:[['bakery-order-type','Mid-fidelity order setup'],['bakery-products','Product selection and current order'],['bakery-customize','Cake customization']]},
{title:'Create a deliberate review step',text:'The review screens bring the selected items, edit and remove actions, subtotal, delivery, and total together before payment. Comparing the low- and mid-fidelity stages shows the development of this information hierarchy. Confirmation closes the flow with an explicit completion state.',images:[['bakery-low-review','Low-fidelity order review'],['bakery-review','Mid-fidelity order review'],['bakery-confirmation','Order confirmation']]}
],outcome:'This project demonstrates how a detailed service task can become a structured interface: stage the decisions, preserve the order context, and provide an opportunity to review. The supplied work is wireframe design, without documented testing results.',source:'Academic concept. Original files: Bakery app stage 1 low fidelity wireframe.fig and Bakery app stage 2 mid fidelity .fig. Placeholder image areas are part of the original wireframes.'},
{slug:'loaded-accessibility',title:'Loaded Accessibility Review',category:'Accessibility · Interface analysis',role:'Accessibility review & annotation',format:'Annotated page reconstructions',summary:'Making potential accessibility issues visible across an e-commerce journey.',deck:'An annotated design review of homepage, product, and checkout patterns, organized into five accessibility considerations.',cover:['loaded-homepage'],tone:'lime',overview:'This academic review uses reconstructed page layouts to identify potential barriers across an e-commerce journey. Lettered annotations connect individual interface elements to a shared review legend.',sections:[
{title:'Organize the review into actionable categories',text:'The annotations cover A: color contrast, B: alternative text, C: keyboard focus, D: form labels, and E: heading hierarchy. Grouping findings this way makes the review easier to trace across multiple pages.',images:[['loaded-homepage','Annotated homepage reconstruction'],['loaded-legend','Accessibility annotation legend']]},
{title:'Follow the task through checkout',text:'The review extends from browsing to a product page and checkout, where controls and form fields become central to completing the task. The annotations highlight questions to investigate in implementation, including whether inputs have accessible labels and interactive elements have a visible focus state.',images:[['loaded-product','Annotated product page'],['loaded-checkout','Annotated checkout']]}
],outcome:'The deliverable demonstrates accessibility awareness and a repeatable annotation method. A design file can identify potential issues; verifying contrast, alternative text, keyboard behavior, and semantic structure requires inspection of the implemented website.',source:'Independent academic review of loaded.com, not commissioned client work or a certification of the live site. Original file: loaded accessibility audit.fig.'},
{slug:'phoenix',title:'City of Phoenix',category:'Responsive UX · Wireframe study',role:'Interface analysis & wireframe recreation',format:'Desktop and mobile page wireframes',summary:'Studying how a content-rich city website organizes services across screen sizes.',deck:'A low-fidelity reconstruction of a city website, examining hierarchy and the relationship between desktop and mobile layouts.',cover:['phoenix-desktop','phoenix-mobile'],tone:'sand',overview:'A city website serves many needs at once: residents looking for services, businesses finding resources, and visitors exploring the city. This study recreates that breadth as long-form desktop and mobile wireframes.',sections:[
{title:'Map a layered information hierarchy',text:'The desktop study combines audience navigation, service shortcuts, seasonal heat-relief information, news, and government resources. Actions such as paying, reporting an issue, finding trash information, and locating a park sit within a much larger page structure.',images:[['phoenix-desktop','Full desktop wireframe · 1440 px wide']],long:true},
{title:'Translate the hierarchy to a narrow screen',text:'The 390 px mobile wireframe studies how the same content can stack vertically. Comparing it with the 1440 px desktop layout makes the changes in grouping, density, and reading order visible. Scroll through either image or open it at full size to inspect the entire page.',images:[['phoenix-mobile','Full mobile wireframe · 390 px wide']],long:true}
],outcome:'This study demonstrates responsive wireframing and the analysis of a large information hierarchy. It is a recreation exercise, rather than a commissioned redesign or a measured improvement to the city’s website.',source:'Independent academic study. Original file: city of phoenix low fi wireframe recreation.fig.'},
{slug:'ai-driving',title:'AI Driving',category:'Senior project · Web design & development',role:'Website design & HTML/CSS development',format:'Complete four-page website concept',summary:'Designing and building a website that introduces autonomous-driving technology.',deck:'A complete student website concept, connecting an introductory landing page with About, Services, and Contact pages.',cover:['/assets/ai-driving.png'],tone:'green',overview:'For my senior project, I designed and built AI Driving, a hypothetical autonomous-driving brand website. The project connects page structure and visual design with a working HTML and CSS implementation.',sections:[
{title:'Begin with structure and navigation',text:'My design-process report describes an initial HTML prototype before CSS styling. I used that stage to work through button placement, images, and navigation, giving the website a structure before developing its visual treatment.'},
{title:'Refine the presentation across devices',text:'The report records checks on laptop, desktop, and mobile, followed by refinements to the design. Darker blues and grays reinforce the technology theme, while the Home, About, Services, and Contact pages separate the introduction from supporting information.'},
{title:'Explore the complete website',text:'The original four-page website is available here, including its navigation and supporting pages. Open it to explore the full project, or read the original three-page report for the documented design process.'}
],outcome:'This project demonstrates taking a website from a structural prototype into an HTML/CSS implementation. It connects visual hierarchy, navigation, and front-end development in a complete deliverable.',source:'Academic concept for a hypothetical brand. Technology and performance statements are concept copy, not validated product claims. The contact form is a demonstration and does not send messages. Sources: AI driving website folder and design process.pdf.'}
];
